export const cars = [
  {
    id: 1,
    name: "Honda City",
    category: "Sedan",
    pricePerDay: "$45",
    images: [
      "/cars/honda-city-front.png",
      "/cars/honda-city-side.png",
      "/cars/honda-city-back.png",
    ],
    seats: 5,
    transmission: "Manual",
    description: "Reliable sedan perfect for city rides.",
  },
  {
    id: 2,
    name: "Toyota Fortuner",
    category: "SUV",
    pricePerDay: "$75",
    images: [
      "/cars/toyota-fortuner-front.png",
      "/cars/toyota-fortuner-side.png",
      "/cars/toyota-fortuner-back.png",
    ],
    seats: 7,
    transmission: "Manual",
    description: "Reliable SUV perfect for city rides.",
  },
  {
    id: 3,
    name: "BMW 7 Series",
    category: "Luxury",
    pricePerDay: "$150",
    images: [
      "/cars/bmw-7-front.png",
      "/cars/bmw-7-side.png",
      "/cars/bmw-7-back.png",
    ],
    seats: 5,
    transmission: "Automatic",
    description: "Reliable Luxury sedan perfect for city rides.",
  },
  {
    id: 4,
    name: "Maruti Swift",
    category: "Hatchback",
    pricePerDay: "$30",
    images: [
      "/cars/maruti-swift-front.png",
      "/cars/maruti-swift-side.png",
      "/cars/maruti-swift-back.png",
    ],
    seats: 5,
    transmission: "Manual",
    description: "Reliable Hatchback perfect for city rides.",
  },
  {
    id: 5,
    name: "Mercedes-Benz C-Class",
    category: "Luxury",
    pricePerDay: "$120",
    images: [
      "/cars/mercedes-front.png",
      "/cars/mercedes-side.png",
      "/cars/mercedes-back.png",
    ],
    seats: 5,
    transmission: "Automatic",
    description: "Reliable Luxury sedan perfect for city rides.",
  },
  {
    id: 6,
    name: "Hyundai Creta",
    category: "SUV",
    pricePerDay: "$50",
    images: [
      "/cars/hyundai-creta-front.png",
      "/cars/hyundai-creta-side.png",
      "/cars/hyundai-creta-back.png",
    ],
    seats: 5,
    transmission: "Manual",
    description: "Reliable SUV perfect for city rides.",
  },
  {
    id: 7,
    name: "Audi A4",
    category: "Luxury",
    pricePerDay: "$140",
    images: [
      "/cars/audi-a4-front.png",
      "/cars/audi-a4-side.png",
      "/cars/audi-a4-back.png",
    ],
    seats: 5,
    transmission: "Automatic",
    description: "Reliable Luxury sedan perfect for city rides.",
  },
  {
    id: 8,
    name: "Kia Seltos",
    category: "SUV",
    pricePerDay: "$70",
    images: [
      "/cars/kia-seltos-front.png",
      "/cars/kia-seltos-side.png",
      "/cars/kia-seltos-back.png",
    ],
    seats: 5,
    transmission: "Automatic",
    description: "Reliable SUV perfect for city rides.",
  },
  {
    id: 9,
    name: "Tesla Model S",
    category: "Electric",
    pricePerDay: "$160",
    images: [
      "/cars/tesla-s-front.png",
      "/cars/tesla-s-side.png",
      "/cars/tesla-s-back.png",
    ],
    seats: 5,
    transmission: "Automatic",
    description: "Luxury electric sedan with top performance.",
  },
  {
    id: 10,
    name: "BMW X5",
    category: "SUV",
    pricePerDay: "$180",
    images: [
      "/cars/bmw-x5-front.png",
      "/cars/bmw-x5-side.png",
      "/cars/bmw-x5-back.png",
    ],
    seats: 7,
    transmission: "Automatic",
    description: "Premium SUV with comfort and power.",
  },
];
